### ISSUE TITLE
Comment box displayed when not logged in

### ISSUE THREAD

**Issue by lshort2** [finchMFG/dewritoHub#15]
When not logged in, an option displays to comment, but does not actually do anything

![screen shot 2018-05-20 at 10 36 34 pm](https://user-images.githubusercontent.com/17188013/40292150-5b0f8b18-5c7e-11e8-87b9-2782b34cf0be.png)

**Comment by finchMFG** [comment]
Oh no, that's no good! I'll fix that! Cheers!

**Comment by finchMFG** [comment]
Fixed in latest commit ( forgot to tag in message )
