### ISSUE TITLE
Instructions on how to run this locally?

### ISSUE THREAD

**Issue by rogersachan** [finchMFG/dewritoHub#2]

**Comment by finchMFG** [comment]
Hi there! My install script got hit by gitignore.

To run locally: 

* Clone repo
* Install Meteorjs
* CD into repo 
* Run: `meteor` in terminal / cmd
 It'll tell you it's missing the required NPM packages, follow the instructions on screen ( usually something like `meteor npm install --save lotsofpacakagesgere` )

Go to localhost:3000 to see the app!

I'll commit proper server install instructions + automatic script tomorrow!

**Comment by rogersachan** [comment]
Feel free to close my issue once this lands. Thanks for making such a cool project!
